version: '3.8'

services:
  gorunner:
    image: marattttt/new_portfolio:gorunner
    ports:
      - "${GORUNNER_PORT}:3001"
    networks:
      - runner_net

  gateway:
    image: marattttt/new_portfolio:gateway
    build:
      context: ./gateway
    ports:
      - "3030:3030"

    environment:
      - GORUNNER_URL=${GORUNNER_URL:-http://gorunner}
    networks:
      - runner_net

networks:
  runner_net:
    driver: bridge
